name: flannel-images

on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: pwsh
        working-directory: ./kubeadm/flannel
    steps:
    - uses: actions/checkout@v2
    - name: Build and push images
      run: |
        echo "${{ secrets.DOCKER_SECRET }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        $gittag = '-'+(($env:GITHUB_REF -split '/' | select-object -skip 2) -join '-')
        ./build.ps1 -push -tagSuffix $gittag
