name: flannel-images

on: [push]
  pull_request:
    paths:
      - "kubeadm/flannel/**"
      - "kubeadm/buildx.psm1"
      - ".github/workflows/flannel.yml"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: pwsh
        working-directory: ./kubeadm/flannel
    steps:
    - uses: actions/checkout@v2
    - name: Build images (without push)
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        ./build.ps1
